blank_issues_enabled: false
contact_links:
  - name: "Get Support"
    url: "https://discord.gg/nWNVCPY"
    about: "Need help to use the project or have a question about it? Join our Discord server!"
